# Profiles:
# - timesscale
# - pgadmin
# - grafana
# - nodered
# - dockpeek
# - dockhand
# - glances
# - core:
#     - timescale
#     - grafana
#     - nodered
# - admin:
#     - pgadmin
#     - dockhand

services:
  db:
    image: timescale/timescaledb:latest-pg16
    container_name: timescale-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: "appdb"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal
    profiles:
      - timescale
      - core

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@bs.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    ports:
      - "127.0.0.1:5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - internal
    profiles:
      - pgadmin
      - admin

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    environment:
      GF_SECURITY_ADMIN_USER: "admin"
      GF_SECURITY_ADMIN_PASSWORD: "admin"
      GF_AUTH_ANONYMOUS_ENABLED: "True"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      GF_SERVER_ROOT_URL: "%(protocol)s://%(domain)s/grafana/"
      GF_SERVER_DOMAIN: "localhost"
      GF_SERVER_SERVE_FROM_SUB_PATH: "True"
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - internal
    profiles:
      - grafana
      - core

  nodered:
    image: nodered/node-red:latest
    container_name: nodered
    restart: unless-stopped
    ports:
      - "127.0.0.1:1880:1880"
    volumes:
      - nodered_data:/data
    networks:
      - internal
    profiles:
      - nodered
      - core

  dockpeek:
    image: dockpeek/dockpeek:latest
    container_name: dockpeek
    environment:
      - SECRET_KEY=your_secure_secret_key
      - DISABLE_AUTH=TRUE
    ports:
      - "3420:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    profiles:
      - dockpeek

  dockhand:
    image: fnsys/dockhand:latest
    container_name: dockhand
    restart: unless-stopped
    user: "0:0"
    ports:
      - 8080:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - dockhand_data:/app/data
    profiles:
      - dockhand
      - admin

  glances:
    image: nicolargo/glances:latest-full
    container_name: glances
    restart: unless-stopped
    pid: host
    network_mode: host  # default port 61208
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /run/user/1000/podman/podman.sock:/run/user/1000/podman/podman.sock
    environment:
      - "GLANCES_OPT=-w"
    #  - "GLANCES_OPT=-w -B 127.0.0.1"
    #  - "GLANCES_OPT=-w -p 8080"
    #  - "GLANCES_OPT=-w -B 127.0.0.1 -p 8080"
    profiles:
      - glances

volumes:
  postgres_data:
  pgadmin_data:  
  grafana_data:
  nodered_data:
  portainer_data:
  dockhand_data:

networks:
  internal:
    driver: bridge
